
version: "3"
services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    network_mode: bridge
    volumes:
      - .:/etc/wireguard
    environment:
      # 필수 파라미터 EIp
      - WG_HOST=43.202.26.173
      - PASSWORD=Papyrus1!
      # Route53 resolver 주소
      - WG_DEFAULT_DNS=192.168.133.242, 192.168.152.190, 1.1.1.1, 0.0.0.0
      - WG_DEVICE=eth0
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1